### ISSUE TITLE
lock template missing keys declaration

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#120]
### Problem

lock template missing keys declaration

### Context

https://github.com/comcode-org/hackmud_wiki/blob/main/templates/lock.mdx

`c003 requires three arguments to fully solve: (( %Nc003%, %Nc003_triad_1%, and %Nc003_triad_2%. ))`

**Comment by kbinreallife** [comment]
Lock template was updated elsewhere, closing issue.
