### ISSUE TITLE
decide content cutoff

### ISSUE THREAD

**Issue by kbinreallife** [comcode-org/hackmud_wiki#15]
### description
come to a decision about amount of content we consider as a baseline to populate wiki
do we include t2? events? characters? etc

### docs?
document decisions about what we include (documented in issue and project board)
~~we discuss this in the issue and put summary of decisions in document~~

### how to validate?
~~decision is made, 5 people have had 3 days to review proposed and decision doc~~
Issue proposal / existing project planning process; any items updated that need scoping / cutoff info.

### what work do we need to do to notify people about this work being completed?
~~announce start and end in project post~~

**Comment by seanmakesgames** [comment]
Proposal: We will announce the wiki once the items in project 9 are complete. This includes, scripts.lib, t1 locks, scripts.trust, to name some.

**Comment by seanmakesgames** [comment]
Close this item once you (someone on the project) read and agree. @ghambhackmud or @danswann maybe

**Comment by danswann** [comment]
Seems reasonable, and in line with what has been discussed previously during meetings.
This should be enough to dial in a workflow that will facilitate adding any and all post-P009 content we would want.
