### ISSUE TITLE
We need to decide how to organize non-lock upgrades

### ISSUE THREAD

**Issue by kbinreallife** [comcode-org/hackmud_wiki#219]
### Problem

Organizing the non-lock upgrades in folders by type does not seem intuitive to navigate for new players.

### Context

We need to make a decision about organization that is both intuitive to navigate for new players, and in a way that makes sense for more veteran players.

- [x] #220

**Comment by seanmakesgames** [comment]
discussed this in discord-- We'll split the upgrades section into class name.

**Comment by kbinreallife** [comment]
Organize by class, see comment on #220

**Comment by kbinreallife** [comment]
folders created
