### ISSUE TITLE
document t1 locks

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#22]
### description
a page for every t1 lock
definitely data_check_v1 and any other t1 versions of locks

### implementation?
- wiki pages for t1 pages

### how to validate?
use pr review process for wiki content

### dependencies?
- [x] #15
- [x] #19
- [x] #113
- [x] #92
- [x] #93
- [x] #95
- [x] #114
- [x] #115
- [x] #96
- [x] #97
- [x] #98
- [x] #99
- [x] #100

**Comment by danswann** [comment]
Separated into issues for each T1 lock. Probably want to revisit the three pre-existing ones by the end of it, in case we refine the Content Guide while writing the rest of them.

**Comment by seanmakesgames** [comment]
All locks added!
