### ISSUE TITLE
create transfer_v1 upgrade page

### ISSUE THREAD

**Issue by kbinreallife** [comcode-org/hackmud_wiki#228]
### Problem

We are missing transfer_v1 on the wiki. There are no t1 scavenger upgrades so we are missing a folder as well.

### Context

Folder cannot be created without files inside of it.

**Comment by seanmakesgames** [comment]
This is a good call-out, but can you convert this issue to just one of the t2 upgrades that falls into that category? like a 'create X.mdx' and just make sure the info that it should be under the scavenger folder is in the body of the issue somewhere as context--
