### ISSUE TITLE
Create sidebar with title "Glossary"

### ISSUE THREAD

**Issue by oolu4236** [comcode-org/hackmud_wiki#252]
### Problem

There's no Glossary sidebar in Hackmud Wiki. A file has been created which contains Jargons and definitions in Lore/Character/Jargon temporarily.

### Context

Moving Jargon from Lore/Character to a "Glossary" sidebar.js would make Jargon easily assessable

**Comment by seanmakesgames** [comment]
Yep! Agreed. I wonder if people have any ideas about where to include content like this. Seems like something that would go with the FAQs that are planned as well. I don't know where those are planned to go.

**Comment by seanmakesgames** [comment]
marto and I discussed a bit in discord
https://discord.com/channels/229545531104296960/1165951912173117580/1203015085434478594
(he's gonna add the idea)

**Comment by matr1x-hackmud** [comment]
We've talked about how the sidebar would be structured to contain a glossary, and my take is that it would fit best under a "Guides" topbar category which looks like this:

```
Guides ->
  New Players ->
    Cool Things To Do!
    Jargon *********
    How do I PCM?
    etc
  Game Content ->
    T1 Corps
    How2 Gibson
  Scripting ->
    // various guides for doing scripting stuff
    // ...
    // ...
```

The category seems like the best place for "subjective" content in general; which jargon falls under by way of being community-curated lingo
