### ISSUE TITLE
basic vlan faq

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#26]
### problem
players have a lot of common questions in the vLAN

### description
an FAQ that answers a few basic questions like:
- dog?
- blue?
- firewall?
- multi-users?
- how do i JAY-SAHN?

### implementation?
- wiki page

### how to validate?
use pr review process for wiki content

### dependencies?
- [x] #19

**Comment by Fayti1703** [comment]
With the introduction of the marks system, the vLAN was (temporarily) removed, so this issue doesn't seem relevant anymore.

**Comment by Spanospy** [comment]
> With the introduction of the marks system, the vLAN was (temporarily) removed, so this issue doesn't seem relevant anymore.

Yeah, even if/when we bring it back, it's not going to be the blocker / teacher that it once was. I don't see a need for an FAQ on something optional.

**Comment by seanmakesgames** [comment]
Yep. Agree.
