### ISSUE TITLE
document upgrades

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#27]
### description
All of the t1 upgrades
- not glams
- not locks

We will also need to consider if/how to handle redirects in the case of multi-tier upgrades, e.g. `char_count_v1` -> `char_count`.

### implementation?
- wiki pages

### dependencies?
- [x] #15
- [x] #19

**Comment by kbinreallife** [comment]
This should be complete once the open PRs are merged :)

**Comment by seanmakesgames** [comment]
confirmed by counting
