### ISSUE TITLE
Select and use a custom domain

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#30]
### description
allows us to have wiki.hackmud.com
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

### implementation?
- wiki.hackmud.com points to our wiki deployment

### how to validate?
- go to wiki.hackmud.com

### dependencies?
- [x] #29

**Comment by danswann** [comment]
Need to update the `baseUrl` in `docusaurus.config.js` before closing this out, so that the deployed site is served from the correct path.

**Comment by danswann** [comment]
> Need to update the `baseUrl` in `docusaurus.config.js` before closing this out, so that the deployed site is served from the correct path.

This is done.

**Comment by danswann** [comment]
I have gone to https://wiki.hackmud.com and validated that it works.
