### ISSUE TITLE
autocolor plugin

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#31]
### problem

Need a way for content creators to be able autocolor in game content.

### description
set up the autocolor rehype plugin for markdown for coloring hackmudthings

colors inside of a color block wrapped in double parens (())
- scripts
- GC strings
- key:value
- %a-zA-Z<text>% color tags

### design?
- add notes to the readme on the wiki for how autocoloring works (and optionally add why it was chosen that way)

### tests?
- unit tests (TDD)

### implementation?
- rehype plugin

### how to validate?
- review of test case stuff

### dependencies?
- [x] #34

**Comment by danswann** [comment]
Closed by #75
