### ISSUE TITLE
decide what should be on the navbar

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#33]
### description
what categories or pages do we want linked in our top navigation

### implementation?
check code in
#13

### how to validate?
pull down branch, run and manually test by at least 1 reviewer before merge

### dependencies?
- [ ] #12 (create pages that navbar links to)

**Comment by ghambhackmud** [comment]
As it exists in #13 this would add a navbar with 1 level of menus. 
upgrades -> t1 locks
lore -> characters, events
scripting -> scripts.lib

If anyone has suggestions or proposal for including something in the preliminary implementation, please leave feedback.

**Comment by matr1x-hackmud** [comment]
> If anyone has suggestions or proposal for including something in the preliminary implementation, please leave feedback.

I think there should be a "guides" part of the navbar for the handful of guides we plan to make (vLAN, new players, scripting etc.)

"upgrades" can probably be broken into:

Upgrades
- Locks
  - T1
  - T2
  - ...
- Script Space
- PvP
- Bot_brains
- ...
There's some considerations to be made about here when considering if we want a page for each version of the same upgrade, or a single page for each version - cuz a lot of upgrade types (bot_brain, channel) only have 1 upgrade

**Comment by ghambhackmud** [comment]
We can get 1 level pretty easily but I think there was issues getting 2 level, like in the upgrades -> locks -> t1. 

The other consideration is the "real estate" or how crowded we want the navbar to be. I personally think that having "Locks, Script Space, PvP, Bot_brains, Characters, Events, Guides, Scripting Reference" all at the top level is way too much.

As for the various pages, I do agree we should discuss that but I'm not sure if this is the right place for it.

**Comment by matr1x-hackmud** [comment]
> We can get 1 level pretty easily but I think there was issues getting 2 level, like in the upgrades -> locks -> t1.
If there's an issue with making multi-level navbars work then "upgrades", "lore" and "scripting" make sense to start with. We'll have to see how the navbar impl shakes out. scripts.lib in particular seems like it'll be an interesting case because of how "big" it is.

> The other consideration is the "real estate" or how crowded we want the navbar to be. I personally think that having "Locks, Script Space, PvP, Bot_brains, Characters, Events, Guides, Scripting Reference" all at the top level is way too much.
Agreed, though I'm of course not suggesting we put bot_brains on the top level and such. "Upgrades" vs "locks" feels like it could be fine having a distinction though - because locks are an upgrade but they are also major content.

> As for the various pages, I do agree we should discuss that but I'm not sure if this is the right place for it. Maybe #16 or #17 ?
Implementation details for the pages are good to go on #16 and #17 - im just concerned about where the completed versions will show up on the navbar in this instance.

My other major though is "do we want to document corps too?" - I suspect #15 and #14 will guide us to the answer to this, but just thinking in terms of formatting if we would want a top level "content" tab that would include "corps", "locks", "events" etc

**Comment by tukib** [comment]
I like the idea of having more high level references to content, i.e. locks over t1 locks, and I agree that locks have a meaningful difference to upgrades.

The initial three categories (upgrades, lore, scripting) I think capture most of what would belong in a shortcuts section, and I do think the top level real-estate should be kept to about 3-4 items. I'll note that if other sections are easily navigable then I feel that we don't need to be too comprehensive or adhere to a strict hierarchy of articles in the navbar.

My suggestion is that content could be organised into "Hacking", "Lore" and "User" (or system?). To me I feel it would grab a new player's attention more. Example below, specific pages obviously depend on the work items you both have mentioned.

<details><summary>Hacking (core "progression" most follow)</summary>

- Locks
- NPCs
- PvP
- Scripting

</details>
<details><summary>Lore (may answer "why" a new player should be motivated to progress)</summary>

- Events
- Characters

</details>
<details><summary>System/User? (answers "how" a player tracks their progress)</summary>

- System Specs
- Upgrades
- Scripting

</details>

some thoughts on this: As much as I feel scripting is a core feature, I'm not sure whether this is better as its own category or referenced within both hacking and user as it is typically used for those, and scripting doesn't have as much substance as the other categories itself. I'm also not sure whether guides should have its own category, and if we link to specific guides "How to hack other online player" or pages that list relevant guides (e.g. Hacking->Guides leads to "Hacking Guides" page)

**Comment by ghambhackmud** [comment]
Oops, sorry for the mass actions here. We were discussing organization and using this as an example.



> My suggestion is that content could be organised into "Hacking", "Lore" and "User" (or system?). To me I feel it would grab a new player's attention more. Example below, specific pages obviously depend on the work items you both have mentioned.

This seems like something that would be good for the contents of the home page but I think a more blatant and categorical listing on the navbar works better to this end. While locks are primary content, they are also upgrades. I'm not sure I'm in favor of mushing and separating navigation into arbitrary categories.




> I'm also not sure whether guides should have its own category, and if we link to specific guides "How to hack other online player" or pages that list relevant guides (e.g. Hacking->Guides leads to "Hacking Guides" page)

I was thinking that we would have some sort of "write ups, articles, or something" category that would include things like the FAQs or literal guides, but also under subcategories for things like write ups for how someone implemented QRs or whatever lecture format information potentially could be made. They'd be collected under their respective category, "guides but better name", but also into their subcategories, maybe?, like guides, write ups, new player help, whatever.

**Comment by tukib** [comment]
> This seems like something that would be good for the contents of the home page but I think a more blatant and categorical listing on the navbar works better to this end. While locks are primary content, they are also upgrades. I'm not sure I'm in favor of mushing and separating navigation into arbitrary categories.

Yeah, on the same page with you here. Assuming the home page is friendly to new players, then I don't think we need to be duplicating entries to where they might be useful/related. So with that in mind, I agree locks does not need to be top level, and the example I gave would be better suited elsewhere.

> I was thinking that we would have some sort of "write ups, articles, or something" category that would include things like the FAQs or literal guides, but also under subcategories for things like write ups for how someone implemented QRs or whatever lecture format information potentially could be made. They'd be collected under their respective category, "guides but better name", but also into their subcategories, maybe?, like guides, write ups, new player help, whatever.

Absolutely, I do think having a guides/help category should included with the initial items (upgrades, lore, scripting). The example subcategories you've listed sound great to me and we can obviously refine what we are expecting here in #16 (or whichever task you think is more appropriate).

**Comment by seanmakesgames** [comment]
Couple things:
I think status of this one should be 'in-progress', right?
I also think we're at a spot where we can cut a proposal for people to provide dissent / feedback for-- right?
