### ISSUE TITLE
scripts.lib titles are too long

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#357]
### Problem

some scripts.lib function names are very long and get cut off or wrapped even on large format displays.

<img width="1270" alt="scripts_lib___get_security_level_name_____hackmud_Wiki" src="https://github.com/comcode-org/hackmud_wiki/assets/568152/2f4de96a-285b-4dd5-9f3d-5f6e0f183938">

### Context

probably we don't need to prefix every function name with scripts.lib() and that would save plenty of space.

**Comment by ellipsisasterisk** [comment]
how about with just the dot?
![firefox_deD0htLJpN](https://github.com/comcode-org/hackmud_wiki/assets/22778008/2e17558e-d1f2-4ac9-8694-25584097a0c7)

**Comment by seanmakesgames** [comment]
Looks cool! Would want to see how it looks in all the places (and the url, etc) Make a PR-
