### ISSUE TITLE
Autocolor plugin effects are not properly isolated inside `(( ))`

### ISSUE THREAD

**Issue by danswann** [comcode-org/hackmud_wiki#363]
### Problem
When the autocolor plugin is applied to a subset of text in a paragraph, the entire paragraph is processed -- beyond what was delimited with `(( ))`.
![image](https://github.com/comcode-org/hackmud_wiki/assets/1775803/19835dde-4c98-4d1d-826b-ff370b316927)

### Context
Looking back at my code from a few months ago, I don't know why I thought this would work. :P
Should be a quick fix, and allow us to start using the plugin without ruining entire paragraphs of text.

**Comment by seanmakesgames** [comment]
Looks good. Thanks for filing!
