### ISSUE TITLE
announce wiki launch more widely

### ISSUE THREAD

**Issue by seanmakesgames** [comcode-org/hackmud_wiki#405]
### Problem

We've posted the wiki to the discord and got some initial feedback-- but we need to start working on our SEO. 

### Context

We need to post to a handful of hackmud owned social locations and other web locations

- [ ] hackmud forums news post
- [ ] steam announcement
- [ ] reddit
- [ ] other places?

* [x]  add it somewhere in the client (probably the boot-up text? in-game users/trust script mirror?)
* [ ] xitter
* [ ] direct submitting of the URL to search engine provider (google's SEO console can be powerful)

**Comment by matr1x-hackmud** [comment]
* [ ]  add it somewhere in the client (probably the boot-up text? in-game users/trust script mirror?????)
* [ ] xitter
* [ ] directly submitting the URL to google (i think theres a thing for this)?

**Comment by Fayti1703** [comment]
A link has been added to the client bootup text as of v2.008. I've marked that task as complete.

**Comment by seanmakesgames** [comment]
Thanks. I think this issue is ded. <3 People will find the wiki when they need it. We own SEO, too now.
