### ISSUE TITLE
Website is not linked to in the repository

### ISSUE THREAD

**Issue by Fayti1703** [comcode-org/hackmud_wiki#424]
### Problem

There's no direct link from the repository to the deployed wiki page, making navigation from here to there harder.

### Context

GitHub has a "repository details" field for a website link:

![image](https://github.com/comcode-org/hackmud_wiki/assets/5366784/4481e88f-af08-40eb-b895-3968aaee114a)

This can only be modified by an authorized user.

**Comment by seanmakesgames** [comment]
Should be complete now. take a look and close if true.

**Comment by Fayti1703** [comment]
Confirmed!
