### ISSUE TITLE
Upgrade pnpm lockfile version

### ISSUE THREAD

**Issue by danswann** [comcode-org/hackmud_wiki#484]
### Problem
Project is using the old `pnpm` lockfile version (v6). `pnpm` v9 introduced a new lockfile version (v9).

Anyone using a fresh install of `pnpm` (including in our Codespaces on this repo) will attempt to upgrade the lockfile to the new standard whenever adding packages or even just running `pnpm install`, causing confusion and unnecessary diffs

### Context
- Upgrade `PNPM_INSTALL_VERSION` in GitHub Actions runners to v9
- Run `pnpm install` with a sufficiently new version of `pnpm` to migrate our lockfile to the new version
- Consider using the optional package manager version specifier syntax in `package.json` so that contributors on older versions of `pnpm` will be prompted to upgrade rather than be confused why they can't read the lockfile

**Comment by seanmakesgames** [comment]
let's do it.
