### ISSUE TITLE
Internal Links are broken

### ISSUE THREAD

**Issue by Fayti1703** [comcode-org/hackmud_wiki#489]
### Problem

![Partial screenshot of the kernel.hardline page, with raw `[[`/`]]` formatting](https://github.com/user-attachments/assets/f9d495f4-666c-4950-8121-635682b47131)

![Partial screenshot of the Marks System page, with raw `[[`/`:`/`]]` formatting](https://github.com/user-attachments/assets/1f0709b4-80ad-4bcd-8a00-6745d2256b8c)

**Comment by matr1x-hackmud** [comment]
Internal links seem to be working in dev environments (including up-to-date local copies and Github Codespaces). It's possible that the production instance has out of date packages somehow?

**Comment by tukib** [comment]
An archived page shows wikilinks working up to 4th of November: https://web.archive.org/web/20241104230932/https://wiki.hackmud.com/guides/new_players/getting_started/
![image](https://github.com/user-attachments/assets/eea9d63e-a685-485d-9348-f6ee712665e8)

**Comment by tukib** [comment]
The EOL timeline in #494 matches up with the ci warning logs and the unaffected archived page a week prior. It could explain why local & dev container builds are unaffected.

**Comment by Fayti1703** [comment]
Apparently fixed by #494
