### ISSUE TITLE
Proposal for hackmud itself: turning strings into callable scriptors, safely.

### ISSUE THREAD

**Issue by zarutian** [comcode-org/hackmud_wiki#500]
I am not sure this is the right place for proposing addition to hackmud itself but I am doing it anyway.

Many folks have asked for a way to change strings into scriptors in scripts to be able to call them.

I think I have found a safe way to do so.

The idea is to make the factility available via trust.str_to_scriptor script.
This script exists on all seclevels (fullsec, hisec, midsec, losec, nullsec). Why? I will come to that.
It fails out if called from the hackmud command line by the way.

The script takes one parameter `name` which is of the format "#<seclevel>s.<username>.<scriptname>" and returns a scriptor object. But it will only do so iff the script whose name is given is at same or higher seclevel as the invocation-of/call-to trust.str_to_scriptor used.

For example `#fs.trust.str_to_scriptor({ name: "#ns.trust.me" })` fails whilst `#ns.trust.str_to_scriptor({ name: "#ns.trust.me" })` does not.

Possible implementation:

```js
"use strict"; // es6 syntax&semantics
function (context, args) { // name:"#ns.trust.me"
  var L = #fs.scripts.lib();
  var t0 = (args != null) && (args != undefined);
  if (t0) { t0 = (args.name != undefined); }
  var n = args.name;
  if (t0) { t0 = L.is_str(n); }
  var t1 = n.split("."); // are array comphrensions in es6 ? I assume not.
  t0 = n.length == 3;
  if (!t0) { return { ok: false, msg: "Expecting `Nname` parameter with a string in \"#ns.trust.me\" format." }; }
  var myseclevel = 5; // change this for every seclevel trust.str_to_scriptor is deployed at
  var sl = Number.parseInt(t1[0].replace("#fs", "4").replace("#4s", 4).replace("#hs", "3").replace("#3s", "3").replace("#ms", "2").replace("#2s", "2").replace("#ls", "1").replace("#1s", "1").replace("#0s", "0").replace("#ns", "0"), 10);
  var name = t1.slice(1).join(".");
  var rl = #fs.scripts.get_level({ name: name });
  if ((sl < myseclevel) || (rl < myseclevel)) { return { ok: false, msg: "Given `Nname` must be on the same seclevel or higher than trust.str_to_scriptor is being invoked at" }; }

  var scriptor = get_scriptor(name); // I am assuming get_scriptor() is the same that is used in the hackmud command line or the preproccessing of scripts.
  return { ok: true, scriptor: scriptor }
}
```

Not currently a player but one of the fans of Thor of PirateSoftware and a humble programmer.

The Worm regards.

PS. As hackmud is in the business of sandboxing javascript curious ones might want to check out [this](https://docs.agoric.com/guides/js-programming/hardened-js).

**Comment by matr1x-hackmud** [comment]
Hello @zarutian! Thank you for your interest and for writing this suggestion out in the detail that you have.

Suggestions like these are better suited for the forums under the bugs_features_ideas board:
https://www.hackmud.com/forums/bugs_features_ideas

As such, I'll be closing this issue as this repo specifically pertains to the hackmud wiki.

**Comment by zarutian** [comment]
I though one needed a hackmud account to post on that board.

**Comment by kbinreallife** [comment]
> I though one needed a hackmud account to post on that board.

Hi @zarutian, you're right, we don't have a way for non-players to be able to post to the forums at this time. We (ComCODE) need to talk about a way to recieve these kinds of suggestions (which are awesome btw). Feel free to join us in the official discord, and thank you so much for reaching out, I'll make sure to keep in touch!

**Comment by zarutian** [comment]
Here is a suggestion: make an github repo named hackmud-suggestions and in it have an explainer how to make an github issue on it. Perhaps with the same templating that is used on this one.

ping  @kbinreallife 

Yet again the Worm Regards.
