### ISSUE TITLE
spoiler syntax is unfriendly

### ISSUE THREAD

**Issue by tukib** [comcode-org/hackmud_wiki#61]
### Problem

Current spoiler syntax is not friendly. It requires using HTML tags, and having a consistent template is not possible (e.g. text for "Spoiler" or "Click to reveal", etc)

```mdx
<details>
  <summary>Spoiler</summary>
  spoiler-ed content
</details>
```

Afaik there is no other way to accomplish this without touching Docusaurus configuration, plugins, or react.

### Context

Docusaurus allows us to [customise admonition syntax](https://docusaurus.io/docs/markdown-features/admonitions#customizing-admonitions), which would allow us to implement syntax such as:

```mdx
:::spoiler
spoiler-ed content
:::
```

**Comment by danswann** [comment]
Just a little pedantry: we don't actually have a mandated spoiler syntax yet. The suggestion for using a `<details>` block is in the *proposed* content guide, so we can still get ahead of this if we want, though I don't actually think it's a good idea to block that until an alternative is implemented.

I do agree that once that goes through though, we should probably revisit this syntax. A custom admonition seems like a fine solution, we can just convert it to a `<details>` in the swizzled wrapper if nothing else.

**Comment by seanmakesgames** [comment]
at this time, we don't have evidence of anyone having trouble with writing spoiler blocks, so it is too early to call this an issue. We will know more about the usability of these decisions as people start writing articles.
